from tkinter import *

def prikaziObavijest(v):
    messagebox.showinfo("ZAHVALA",str(v)+" hvala na suradnji!")

glavni = Tk()
oznaka = Label(glavni, text="Unesi ime:")
oznaka.pack()
unos = Entry(glavni)
unos.pack()
tipka = Button(glavni, text="Poruka", command=lambda:prikaziObavijest(unos.get()))
tipka.pack()

glavni = Tk()
c1 = Canvas(glavni, bg="blue", height=200, width=400)
c1.pack(expand=1,fill=BOTH)
c2 = Canvas(glavni, bg="red", height=200, width=400)
c2.pack(expand=1,fill=BOTH)
c11 = Canvas(c1, bg="brown", height=200, width=200)
c11.pack(side=LEFT,expand=1,fill=BOTH )
c12 = Canvas(c1, bg="green", height=200, width=200)
c12.pack(side=LEFT,expand=1,fill=BOTH )
c4 = Canvas(c12, bg="yellow", height=100, width=200)
c4.pack(expand=1,fill=BOTH)
c5 = Canvas(c12, bg="pink", height=100, width=200)
c5.pack(expand=1,fill=BOTH)
c21 = Canvas(c2, bg="green", height=200, width=200)
c21.pack(side=LEFT,expand=1,fill=BOTH )
c22 = Canvas(c2, bg="brown", height=200, width=200)
c22.pack(side=LEFT,expand=1,fill=BOTH )
c6 = Canvas(c21, bg="teal", height=100, width=200)
c6.pack(expand=1,fill=BOTH )
c7 = Canvas(c21, bg="teal", height=100, width=200)
c7.pack(expand=1,fill=BOTH )
c8 = Canvas(c6, bg="orange", height=100, width=100)
c8.pack(side=LEFT,expand=1,fill=BOTH )
c9 = Canvas(c6, bg="green", height=100, width=100)
c9.pack(side=LEFT,expand=1,fill=BOTH )


glavni = Tk()
c1 = Canvas(glavni, bg="brown", height=200, width=200)
c1.grid(row =1,column=1,rowspan=2,columnspan=2)
c2 = Canvas(glavni, bg="yellow", height=100, width=200)
c2.grid(row =1,column=3,columnspan=2)
c3 = Canvas(glavni, bg="pink", height=100, width=200)
c3.grid(row =2,column=3,columnspan=2)
c4 = Canvas(glavni, bg="orange", height=100, width=100)
c4.grid(row =3,column=1)
c5 = Canvas(glavni, bg="green", height=100, width=100)
c5.grid(row =3,column=2)
c6 = Canvas(glavni, bg="teal", height=100, width=200)
c6.grid(row =4,column=1,columnspan=2)
c7 = Canvas(glavni, bg="brown", height=200, width=200)
c7.grid(row =3,column=3,rowspan=2,columnspan=2)

glavni = Tk()
glavni.geometry("400x400")
c1 = Canvas(glavni, bg="brown")
c1.place(height=200, width=200)
c2 = Canvas(glavni, bg="yellow")
c2.place(height=100, width=200,x=200)
c3 = Canvas(glavni, bg="pink")
c3.place(height=100, width=200,x=200,y=100)
c4 = Canvas(glavni, bg="orange")
c4.place(height=100, width=100,y=200)
c5 = Canvas(glavni, bg="green")
c5.place(height=100, width=100,x=100,y=200)
c6 = Canvas(glavni, bg="teal")
c6.place(height=100, width=200,y=300)
c7 = Canvas(glavni, bg="brown")
c7.place(height=200, width=200,x=200,y=200)

def pohrani(ime,pre,god,dat):
    datoteka = open(dat+str(".txt"),"a")
    datoteka.write(str(ime)+" "+str(pre)+" "+str(god)+"\n")
    datoteka.close()
    glavni = Tk()
    oznaka1 = Label(glavni, text="Ime osobe:")
    oznaka1.pack()
    unos1 = Entry(glavni, bd =1)
    unos1.pack()
    oznaka2 = Label(glavni, text="Prezime osobe:")
    oznaka2.pack()
    unos2 = Entry(glavni, bd =1)
    unos2.pack()
    oznaka3 = Label(glavni, text="Godine starosti(1-99):")
    oznaka3.pack()
    unos3 = Spinbox(glavni, from_=1,to=99)
    unos3.pack()
    tipka = Button (glavni, text ="Pohrani podatke", command = lambda:pohrani(unos1.get(),unos2.get(),unos3.get(),unos4.get()))
    tipka.pack()
    oznaka4 = Label(glavni, text="Ime datoteke za pohranu:")
    oznaka4.pack()
    unos4 = Entry(glavni, bd =1)
    unos4.pack()

def pohrani(ime,pre,god,dat):
    datoteka = open(dat+str(".txt"),"a")
    datoteka.write(str(ime)+" "+str(pre)+" "+str(god)+"\n")
    datoteka.close()

def citaj(dat):
    datoteka = open(dat+str(".txt"),"r")
    lista = datoteka.readlines()
    messagebox.showinfo("INFORMACIJA","Datoteka sadrži {0} zapisa".format(len(lista)))
    datoteka.close()
    glavni = Tk()
    oznaka1 = Label(glavni, text="Ime osobe:")
    oznaka1.pack()
    unos1 = Entry(glavni, bd =1)
    unos1.pack()
    oznaka2 = Label(glavni, text="Prezime osobe:")
    oznaka2.pack()
    unos2 = Entry(glavni, bd =1)
    unos2.pack()
    oznaka3 = Label(glavni, text="Godine starosti(1-99):")
    oznaka3.pack()
    unos3 = Spinbox(glavni, from_=1,to=99)
    unos3.pack()
    tipka = Button (glavni, text ="Pohrani podatke", command =lambda:pohrani(unos1.get(),unos2.get(),unos3.get(),unos4.get()))
    tipka.pack()
    oznaka4 = Label(glavni, text="Ime datoteke za pohranu:")
    oznaka4.pack()
    unos4 = Entry(glavni, bd =1)
    unos4.pack()
    tipka2 = Button (glavni, text ="Čitaj", command = lambda:citaj(unos5.get()))
    tipka2.pack()
    oznaka5 = Label(glavni, text="Ime datoteke za čitanje:")
    oznaka5.pack()
    unos5 = Entry(glavni, bd =1)
    unos5.pack()

glavni.geometry("600x300")
c1 = Canvas(glavni)
c1.place(height=150, width=300)
c2 = Canvas(glavni)
c2.place(height=150, width=300,x=300)
c3 = Canvas(glavni)
c3.place(height=150, width=300,y=150)
c4 = Canvas(glavni)
c4.place(height=150, width=300,x=300,y=150)
oznaka1 = Label(c1, text="Ime osobe:")
oznaka1.place(x=40,y=40)
unos1 = Entry(c1, bd =1)
unos1.place(x=140,y=40)
oznaka2 = Label(c1, text="Prezime osobe:")
oznaka2.place(x=40,y=100)
unos2 = Entry(c1, bd =1)
unos2.place(x=140,y=100)
oznaka3 = Label(c2, text="Godine starosti(1-99):")
oznaka3.place(x=20,y=70)
unos3 = Spinbox(c2, from_=1,to=99)
unos3.place(x=150,y=70)
tipka = Button (c3, text ="Pohrani podatke", command =lambda:pohrani(unos1.get(),unos2.get(),unos3.get(),unos4.get()))
tipka.place(x=100,y=40)
oznaka4 = Label(c3, text="Ime datoteke za pohranu:")
oznaka4.place(x=80,y=70)
unos4 = Entry(c3, bd =1)
unos4.place(x=90,y=90)
tipka2 = Button (c4, text ="Čitaj", command = lambda:citaj(unos5.get()))
tipka2.place(x=130,y=40)
oznaka5 = Label(c4, text="Ime datoteke za čitanje:")
oznaka5.place(x=86,y=70)
unos5 = Entry(c4, bd =1)
unos5.place(x=90,y=90)

glavni = Tk()
glavni.geometry("400x400")
c1 = Canvas(glavni, bg="blue")
c1.place(relheight=0.5, relwidth=0.5)
c2 = Canvas(glavni, bg="yellow")
c2.place(relheight=0.25, relwidth=0.5,relx=0.5)
c3 = Canvas(glavni, bg="pink")
c3.place(relheight=0.25, relwidth=0.5,relx=0.5,rely=0.25)
c4 = Canvas(glavni, bg="orange")
c4.place(relheight=0.25, relwidth=0.25,rely=0.5)
c5 = Canvas(glavni, bg="green")
c5.place(relheight=0.25, relwidth=0.25,relx=0.25,rely=0.5)
c6 = Canvas(glavni, bg="teal")
c6.place(relheight=0.25, relwidth=0.5,rely=0.75)
c7 = Canvas(glavni, bg="blue")
c7.place(relheight=0.5, relwidth=0.5,relx=0.5,rely=0.5)
glavni.mainloop()